### ISSUE TITLE
Documentation of Development environment

### ISSUE THREAD

**Issue by cueltschey** [oran-testing/soft-t-ue#16]
We agreed in our meeting that we should have a document laying out what tools we will be using for development.

We need the following explained in the document:
- Python dependency management / poetry
- Clang tidy files to use / proper code formatting
- What repos will we use for each component (should we split components into different repos?)

**Comment by bjones1** [comment]
I'll add my proposal here for discussion by the group; when this is finalized, we can simply copy and paste the Markdown into our repo's documentation.

## Code formatting

A code formatter saves time and reduces frustration for developers, particularly when it's integrated into the IDE:

1. Rather than spend time manually tabbing back and forth when adding or removing a block of code, ensuring that indents are using spaces, nicely word-wrapping long lines, etc. simply press save and let the formatter take care of this for you. 
2. This helps create similar styles across developers. Formatters ensure all files have consistent spacing between operators, braces are in the correct location, consistent quote marks (single or double, for example), etc. are automatically take care of, again without needed to manually track these items down.
3. Formatters can also enforce naming conventions, again helping make code uniform across multiple developers.

For this project, we will use [black](https://black.readthedocs.io/en/stable/) for Python. For C code, we'll follows SRS' coding conventions, using their provided `.clang-tidy` and `.clang-format` files from their repo.

### IDE integration
We'll specifically support VSCode, but welcome contribution for other IDEs. To configure these:

- Install the [Black](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter) VSCode extension, then follow these [setup directions](https://code.visualstudio.com/docs/python/formatting).
- Install the [C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) then set up [code formatting](https://code.visualstudio.com/docs/cpp/cpp-ide#_code-formatting) and [linting](https://devblogs.microsoft.com/cppblog/visual-studio-code-c-december-2021-update-clang-tidy/).

**Comment by cueltschey** [comment]
I just managed to get clang tidy to work, and I gave black a try. I think they both work really well. I have no objections to finalizing these choices.

**Comment by cueltschey** [comment]
@Prab-khnl did a great job of this today, so I am closing the issue.
